### application settings
spring.application.name=speech-bot

### bot settings
bot.token=${OBSERVER_BOT_TOKEN:default-bot-token}
bot.username=${OBSERVER_BOT_USERNAME:default-bot-username}
bot.expiration-seconds=60
