### application settings
spring.application.name=speech-bot

### bot settings
bot.token=${SPEECH_KIT_BOT_TOKEN:default-bot-token}
bot.username=${SPEECH_KIT_BOT_USERNAME:default-bot-username}
bot.expiration-seconds=60

### speech kit setting
speech-kit.api-key=${SPEECH_KIT_BOT_API_KEY:default-api-key}

### grpc settings
grpc.client.speech-kit-grpc.address=stt.api.cloud.yandex.net:443
grpc.client.speech-kit-grpc.negotiation-type=tls
grpc.client.speech-kit-grpc.enable-keep-alive=true
